## 1. ndim 이해하기

In [1]:
import numpy as np

In [1]:
n = np.array(5)
n.ndim # 1차원 배열 - 스칼라 - 0차원이다

0

In [2]:
v = np.array([32, 5, 3, 43, 27]) # 벡터 선언 - 1차원
v.ndim

1

In [3]:
x = np.array([[32, 5, 3, 43, 27], [28, 76, 0, 33, 46], [11, 9, 24, 83, 47]])
# 2차원 벡터 선언

x = np.array([[32, 5, 3, 43, 27],
              [28, 76, 0, 33, 46],
              [11, 9, 24, 83, 47]])

x.ndim

2

In [4]:
x = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]],
              [[21, 22, 23, 24, 25], [26, 27, 28, 29, 30]]])
# 3차원 벡터 선언

x = np.array([[[1, 2, 3, 4, 5], 
               [6, 7, 8, 9, 10]],
              [[11, 12, 13, 14, 15], 
               [16, 17, 18, 19, 20]],
              [[21, 22, 23, 24, 25], 
               [26, 27, 28, 29, 30]]])
x.ndim

3

In [5]:
x.shape

(3, 2, 5)

In [6]:
np.max(x, axis=0)

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [7]:
np.argmax(x, axis=0)
# 최대값의 인덱스를 얻을 때 사용

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]], dtype=int64)

## 2. shape 이해하기

In [9]:
a = np.array([[5,5,5,5,5], [5,5,5,5,5], [5,5,5,5,5]])
a.shape

(3, 5)

In [10]:
a = np.array([[[5,5,5,5,5], [5,5,5,5,5], [5,5,5,5,5]], 
              [[5,5,5,5,5], [5,5,5,5,5], [5,5,5,5,5]]])
a.shape

(2, 3, 5)

### - np.reshape

In [11]:
a.reshape((6,5))

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [12]:
# reshape 에 -1을 입력하면 고정된 차원은 우선 채우고, 남은 부분을 알아서 채워준다.
a.reshape((-1,5))

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [13]:
a.reshape((1,1,2,3,5))

array([[[[[5, 5, 5, 5, 5],
          [5, 5, 5, 5, 5],
          [5, 5, 5, 5, 5]],

         [[5, 5, 5, 5, 5],
          [5, 5, 5, 5, 5],
          [5, 5, 5, 5, 5]]]]])

### - np.ravel

In [14]:
np.ravel(a)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5])

### - np.squeeze

- 차원 중 사이즈가 1인 것을 찾아 스칼라값으로 바꿔서 해당 차원 자체를 제거함

In [15]:
np.squeeze([[[1]],[[2]],[[3]]])

array([1, 2, 3])

### - np.expand_dims
- axis로 지정된 차원을 추가함

In [16]:
np.expand_dims([[1], [2], [3]], axis=0)
# axis = 0 , 즉 x축을 기준으로 차원을 추가한다.

array([[[1],
        [2],
        [3]]])

### - np.stack
- 여러 조각의 행렬을 합칠 때 사용함

In [18]:
x = [1,2]
y = [3,4]
z = [5,6]

np.stack([x, y, z], axis=0)

# 이게 무슨 뜻이냐면,
# 1번째 차원 (index 0)에 차례대로 적재한다는 뜻임
# axis option default는 0

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
np.stack([x,y,z], axis=1)

array([[1, 3, 5],
       [2, 4, 6]])

In [20]:
np.stack([x,y,z])

array([[1, 2],
       [3, 4],
       [5, 6]])

## 3. 브로드 캐스팅 (Broadcasting)

행렬에서의 브로드캐스팅은, 두 행렬 A,B중 크기가 작은 행렬을 크기가 큰 행렬과 모양(shape)이 맞게끔 늘려주는 것을 의미한다.

예를 들어, 아래의 행렬처럼 (3, 3)행렬에 (1, 3)행렬을 더하려고 할 때, (1, 3)행렬을 (3, 3)처럼 확장시켜 주는 것이 바로 브로드캐스팅(Broadcasting)

In [21]:
x = np.array([1,2])
y = np.array(3)

print(x + y)

[4 5]


In [22]:
x = np.array([[1,2]])
y = np.array([3,4])

print(x + y)

[[4 6]]


In [23]:
x = np.array([[1,2], [5,6]])
y = np.array([3,4])

print(x + y)

[[ 4  6]
 [ 8 10]]


In [24]:
x = np.array([[1,2]])
y = np.array([[3],[4]])

print(x + y)

[[4 5]
 [5 6]]


## 4. axis 이해하기

### - np.mean

In [26]:
x = [[1, 2],
     [3, 4]]

In [27]:
print(np.mean(x, axis=0))

[2. 3.]


In [28]:
print(np.mean(x, axis=1))

[1.5 3.5]


In [29]:
print(np.mean(x, axis=-1))
# 마지막 axis 를 반환함
# 이거는 2차원 배열이라서 가장 안쪾(나중)의 차원이 그냥 axis=1이랑 똑같아서 결과가 똑같을뿐

[1.5 3.5]


In [30]:
print(np.mean(x))

2.5


### - np.sum

In [31]:
print(np.sum(x, axis=0))

[4 6]


In [32]:
print(np.sum(x, axis=1))

[3 7]


In [33]:
print(np.sum(x, axis=-1))

[3 7]


In [34]:
print(np.sum(x))

10


### - np.argmax

In [35]:
x = [[0, 1, 2],
     [3, 1, 0]]

In [36]:
print(np.argmax(x, axis=0))

[1 0 0]


In [37]:
print(np.argmax(x, axis=1))

[2 0]


In [38]:
print(np.argmax(x, axis=-1))

[2 0]


In [39]:
print(np.argmax(x))

3


## 점곱(내적, dot-product)

In [40]:
a = np.array([1,2])
b = np.array([10,20])

print(np.dot(a,b))

50


In [41]:
print(a@b)

50


In [42]:
a = np.array([[1,2,3],
             [4,5,6]])
b = np.array([[7,9,11],
             [8,10,12]])

print(np.dot(a,b))

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [43]:
c = b.T
print(c)

print()

print(np.dot(a,c))

[[ 7  8]
 [ 9 10]
 [11 12]]

[[ 58  64]
 [139 154]]


파이썬에서는 0.01, 0.1 같은 숫자를 간편하게 표기하려고
- 1e-2 (1에 10을 곱한것의 -2승) # 0.01
- 10e-2 (10에 10을 곱한것의 -2승) # 0.1

이런식의 표현을 하기도 한다.

### 퍼셉트론 기본 연산으로 표현

In [2]:
import tensorflow as tf
from tensorflow import keras

ImportError: Could not find 'cudart64_100.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 10.0 from this URL: https://developer.nvidia.com/cuda-90-download-archive

In [45]:
keras.layers.Dense(512, activation='relu')

NameError: name 'keras' is not defined

In [ ]:
relu(dot(W, input) + b)

In [ ]:
x = dot(W, input) + b
max(x, 0)